plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/jasondanyliw/Documents/Codex/2026-06-15/build-a-website"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]